name: (Staging) CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  db-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Go Dependencies
        run: go mod tidy

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Create .env File
        run: echo "POSTGRES_DB_URL=${{ secrets.STAGING_POSTGRES_DB_URL }}" > .env

      - name: Run DB Migrations
        run: make db-migrate
